version: '3.8'

services:
  app:
    build: .
    image: mydash:latest
    volumes: 
      - type: bind
        source: ./data
        target: /app/data
    ports:
      - "8080:8501"
    deploy:
      replicas: 1
    networks:
      - mydash-network
    command: streamlit run Home.py
    restart: always

volumes:
  mydata:

networks:
  mydash-network:
